#!/usr/bin/env bash
# ~/.bashrc

# creates new unsigned Chrome extension zip file
pasta() {
  echo "making pasta..."
  zip pasta.zip -r src -x *.git* > pasta.log
  cat pasta.log
  echo "done."
}

# creates new knowledge base key
kbdate() {
  date +"KB%g%j%H%M";
}

## one-word Google App Engine deployment
dunk() {
  VER=$(date +%b%d | tr [:upper:] [:lower:])
  gcloud app deploy -q -v $VER
} 

## one-word Linux package update
upd() {
  sudo apt update;
  sudo apt upgrade -y;
  sudo apt autoremove -y;
}
