#!/usr/bin/env bash
# ~/.bashrc

# creates new unsigned Chrome extension zip file
pasta() {
  echo "making pasta..."
  zip pasta.zip -r src -x *.git* > pasta.log
  cat pasta.log
  echo "done."
}

# creates new knowledge base key
function kbdate() {
  date +"KB%g%j%H%M";
}
